#ifndef AKOYA_MULTIBOOT_H
#define AKOYA_MULTIBOOT_H

#define MULTIBOOT_HEADER_MAGIC      0x1BADB002
#define MULTIBOOT_BOOTLOADER_MAGIC  0x2BADB002
#define MULTIBOOT_HEADER_FLAGS      0x00000000
#define MULTIBOOT_HEADER_CHECKSUM   (-(MULTIBOOT_HEADER_MAGIC + MULTIBOOT_HEADER_FLAGS))

#endif
